apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: opso-project
  namespace: argocd
spec:
  description: OpsO ArgoCD Project
  destinations:
  - namespace: opso
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/jamalshahverdiev/opso.git
