apiVersion: apps/v1
kind: Deployment
metadata:
  name: opso-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: opso
  template:
    metadata:
      labels:
        app: opso
    spec:
      containers:
      - name: opso-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
